### ISSUE TITLE
make sync fails in a new clone

### ISSUE THREAD

**Issue by kevnfx** [PARC/CCNx_Distillery#21]
```
% make sync
Fetching Distillery...
Fetching origin
Already up-to-date.
make: /Users/kfox/Desktop/Dev/CCNx/ws/10-kev-linkModuleTemplate/CCNx_Distillery/tools/syncWithMaster: No such file or directory
make: *** [distillery-sync] Error 1
```

The distillery-sync target should have a dependency on the script it's going to execute, like so:

distillery-sync: distillery-update ${DISTILLERY_ROOT_DIR}/tools/syncWithMaster
        @${DISTILLERY_ROOT_DIR}/tools/syncWithMaster

**Comment by isolis** [comment]
Are you sure this is a bug on the current Distillery?   We fixed that yesterday.

**Comment by isolis** [comment]
Not an issue with the current version
