### ISSUE TITLE
Doxygen dependency build fail on OSX 10.11

### ISSUE THREAD

**Issue by greg80303** [PARC/CCNx_Distillery#9]
I'm running OSX 10.11.3.  I have MacPorts with various utilities already installed, so this may be what's causing the hiccup.  When building doxygen, I get the following failure:
```
/opt/local/bin/flex -i -PvhdlcodeYY -t vhdlcode.l | /usr/bin/python increasebuffer.py > ../generated_src/doxygen/vhdlcode.cpp
c++ -c -pipe -mmacosx-version-min=10.5 -DYY_TYPEDEF_YY_SIZE_T -Dyy_size_t=int -Wall -W -Wno-deprecated-declarations -O3 -I../generated_src/doxygen -I../src -I../qtools -I../libmd5 -I../vhdlparser -o ../objects/doxygen/vhdlcode.o ../generated_src/doxygen/vhdlcode.cpp
In file included from vhdlcode.l:29:
In file included from ../qtools/qregexp.h:42:
In file included from ../qtools/qcstring.h:21:
In file included from ../qtools/qarray.h:42:
In file included from ../qtools/qgarray.h:42:
In file included from ../qtools/qshared.h:42:
../qtools/qglobal.h:105:6: warning: "This version of Mac OS X is unsupported" [-W#warnings]
#    warning "This version of Mac OS X is unsupported"
     ^
vhdlcode.l:1618:2: error: "You seem to be using a version of flex newer than 2.5.4 but older than 2.5.33. These
      versions do NOT work with doxygen! Please use version <=2.5.4 or >=2.5.33 or expect things to be parsed
      wrongly!"
#error "You seem to be using a version of flex newer than 2.5.4 but older than 2.5.33. These versions do NOT w...
```

Checking my version of flex:
```
~/Projects/CableLabs/ICN/CCN/CCNx_Distillery > flex --version
flex 2.6.0
```

So it seems there is something buggy in the doxygen build system, since my flex is not older than 2.5.33.  The current version of doxygen in CCNx_Distillery is 1.8.9.1.  The most recent stable version is 1.8.11, so I tried to update the build system to use that version and it seemed to take care of the problem.  I ran `make all` after my change and all of the HTML documentation seemed to be there, so I think it is working.

I know you guys don't have a format contribution policy yet, but I will create a pull request for my fix in case it helps speed things up.

**Comment by GlennCScott** [comment]
I've merged Greg's fix to this.
